import 'dart:convert';
import 'dart:io';

import 'package:yaml/yaml.dart' as yaml;

class HarnessStateStore {
  HarnessStateStore({
    this.featureListPath = 'feature_list.json',
    this.specsDirectory = 'docs/harness/specs',
  });

  final String featureListPath;
  final String specsDirectory;

  File? acceptanceFile(String id) {
    final nested = File('$specsDirectory/$id/acceptance.yaml');
    if (nested.existsSync()) return nested;

    final flat = File('$specsDirectory/acceptance.yaml');
    if (flat.existsSync()) {
      final doc = yaml.loadYaml(flat.readAsStringSync());
      if (doc is yaml.YamlMap && doc['spec'] == id) return flat;
    }
    return null;
  }

  String specStatus(String id) {
    for (final feature in loadFeatures()) {
      if (feature['spec'] == id) {
        return feature['status']?.toString() ?? 'unknown';
      }
    }
    return 'unlinked';
  }

  bool setSpecStatus(String id, String status) {
    final file = File(featureListPath);
    final decoded = jsonDecode(file.readAsStringSync()) as Map<String, Object?>;
    final features = (decoded['features'] as List<Object?>)
        .cast<Map<String, Object?>>();

    var found = false;
    for (final feature in features) {
      if (feature['spec'] == id) {
        feature['status'] = status;
        found = true;
      }
    }
    if (!found) return false;

    file.writeAsStringSync(const JsonEncoder.withIndent('  ').convert(decoded));
    return true;
  }

  List<Map<String, Object?>> loadFeatures() {
    final raw = File(featureListPath).readAsStringSync();
    final decoded = jsonDecode(raw) as Map<String, Object?>;
    return (decoded['features'] as List<Object?>).cast<Map<String, Object?>>();
  }

  List<String> doneSpecs() {
    return [
      for (final feature in loadFeatures())
        if (feature['status'] == 'done' &&
            feature['spec'] is String &&
            (feature['spec'] as String).isNotEmpty)
          feature['spec'] as String,
    ];
  }

  Map<String, Object?>? featureForSpec(String spec) {
    for (final feature in loadFeatures()) {
      if (feature['spec'] == spec) return feature;
    }
    return null;
  }
}

class HarnessUiMapGenerator {
  const HarnessUiMapGenerator({required this.state});

  final HarnessStateStore state;

  GeneratedUiMap generate() {
    const approvedStatuses = {
      'spec-approved',
      'implementing',
      'accepted',
      'done',
    };
    final targets = <String, Map<String, Object?>>{};
    var specCount = 0;

    for (final feature in state.loadFeatures()) {
      if (!approvedStatuses.contains(feature['status'])) continue;

      final spec = feature['spec'];
      if (spec is! String || spec.isEmpty) continue;

      final deltaFile = File('${state.specsDirectory}/$spec/ui-map.delta.yaml');
      if (!deltaFile.existsSync()) continue;

      specCount += 1;
      final delta = yaml.loadYaml(deltaFile.readAsStringSync());
      if (delta is! yaml.YamlMap || delta['targets'] == null) continue;

      final deltaTargets = delta['targets'] as yaml.YamlMap;
      for (final key in deltaTargets.keys) {
        final targetId = key.toString();
        final rawTarget = deltaTargets[key];
        if (rawTarget is! yaml.YamlMap) {
          throw FormatException(
            'Target "$targetId" in ${deltaFile.path} must be a map.',
          );
        }

        final target = <String, Object?>{};
        for (final field in rawTarget.keys) {
          target[field.toString()] = rawTarget[field];
        }

        final existing = targets[targetId];
        if (existing != null && !_sameMap(existing, target)) {
          throw FormatException(
            'Target "$targetId" is defined differently in ${deltaFile.path}.',
          );
        }
        targets[targetId] = target;
      }
    }

    return GeneratedUiMap(
      content: _formatCanonicalUiMap(targets),
      specCount: specCount,
      targetCount: targets.length,
    );
  }

  bool _sameMap(Map<String, Object?> a, Map<String, Object?> b) {
    return jsonEncode(a) == jsonEncode(b);
  }

  String _formatCanonicalUiMap(Map<String, Map<String, Object?>> targets) {
    final buffer = StringBuffer()
      ..writeln('# Canonical UI target map for harness specs.')
      ..writeln(
        '# Generated by `fvm dart run tool/harness.dart spec ui-map`; do not edit by hand.',
      )
      ..writeln(
        '# Source: approved docs/harness/specs/*/ui-map.delta.yaml files.',
      );

    if (targets.isEmpty) {
      buffer.writeln('targets: {}');
      return buffer.toString();
    }

    buffer.writeln('targets:');
    for (final entry in targets.entries) {
      buffer.writeln('  ${entry.key}:');
      for (final field in entry.value.entries) {
        buffer.writeln('    ${field.key}: ${_formatYamlScalar(field.value)}');
      }
    }
    return buffer.toString();
  }

  String _formatYamlScalar(Object? value) {
    if (value == null) return 'null';
    if (value is num || value is bool) return value.toString();

    final text = value.toString();
    if (_canUsePlainYamlScalar(text)) return text;

    return "'${text.replaceAll("'", "''")}'";
  }

  static final RegExp _leadingPunct = RegExp(r'^[+\-?&*!|>{}\[\],%@`]');
  static final RegExp _reservedWord = RegExp(
    r'^(true|false|null|Null|NULL|~)$',
  );
  static final RegExp _plainScalar = RegExp(r'^[A-Za-z0-9_./() -]+$');

  bool _canUsePlainYamlScalar(String text) {
    if (text.isEmpty || text.trim() != text) return false;
    if (text.contains(':') || text.contains('#')) return false;
    if (_leadingPunct.hasMatch(text)) return false;
    if (_reservedWord.hasMatch(text)) return false;
    if (num.tryParse(text) != null) return false;
    return _plainScalar.hasMatch(text);
  }
}

class HarnessPolicy {
  const HarnessPolicy({
    required this.path,
    required this.version,
    required this.minimumCoverage,
    required this.lowFileCoverageThreshold,
    required this.coverageExcludes,
    required this.expectedMaestroVersion,
    required this.maestroPlatforms,
    required this.iosAppId,
    required this.androidAppId,
    required this.doneCommand,
    required this.buildEvidenceDir,
    required this.committedEvidenceDir,
    required this.requiredEvidenceReports,
    required this.requiredHarnessFiles,
    required this.requiredHarnessDirectories,
    required this.generatedFiles,
    required this.agentSkills,
    required this.acceptanceReportEvents,
  });

  final String path;
  final int version;
  final double minimumCoverage;
  final double lowFileCoverageThreshold;
  final List<CoverageExcludeRule> coverageExcludes;
  final String expectedMaestroVersion;
  final List<String> maestroPlatforms;
  final String iosAppId;
  final String androidAppId;
  final String doneCommand;
  final String buildEvidenceDir;
  final String committedEvidenceDir;
  final List<String> requiredEvidenceReports;
  final List<String> requiredHarnessFiles;
  final List<String> requiredHarnessDirectories;
  final List<String> generatedFiles;
  final List<String> agentSkills;
  final List<String> acceptanceReportEvents;

  static HarnessPolicy load(File file) {
    final doc = yaml.loadYaml(file.readAsStringSync()) as yaml.YamlMap;
    final coverage = doc['coverage'] as yaml.YamlMap;
    final maestro = doc['maestro'] as yaml.YamlMap;
    final appIds = maestro['app_ids'] as yaml.YamlMap;
    final evidence = doc['evidence'] as yaml.YamlMap;
    final harness = doc['harness'] as yaml.YamlMap;
    final observability = doc['observability'] as yaml.YamlMap;

    return HarnessPolicy(
      path: file.path,
      version: (doc['version'] as num).toInt(),
      minimumCoverage: (coverage['minimum_line_percent'] as num).toDouble(),
      lowFileCoverageThreshold: (coverage['low_file_threshold_percent'] as num)
          .toDouble(),
      coverageExcludes: [
        for (final raw in (coverage['exclude'] as yaml.YamlList))
          CoverageExcludeRule.fromYaml(raw as yaml.YamlMap),
      ],
      expectedMaestroVersion: maestro['expected_version'].toString(),
      maestroPlatforms: _stringList(maestro['platforms'] as yaml.YamlList),
      iosAppId: appIds['ios'].toString(),
      androidAppId: appIds['android'].toString(),
      doneCommand: maestro['done_command'].toString(),
      buildEvidenceDir: evidence['build_dir'].toString(),
      committedEvidenceDir: evidence['committed_dir'].toString(),
      requiredEvidenceReports: _stringList(
        evidence['required_reports'] as yaml.YamlList,
      ),
      requiredHarnessFiles: _stringList(
        harness['required_files'] as yaml.YamlList,
      ),
      requiredHarnessDirectories: _stringList(
        harness['required_directories'] as yaml.YamlList,
      ),
      generatedFiles: _stringList(harness['generated_files'] as yaml.YamlList),
      agentSkills: _stringList(harness['agent_skills'] as yaml.YamlList),
      acceptanceReportEvents: _stringList(
        observability['acceptance_report_events'] as yaml.YamlList,
      ),
    );
  }

  static List<String> _stringList(yaml.YamlList list) {
    return [for (final item in list) item.toString()];
  }

  Map<String, Object?> toJson() {
    return {
      'path': path,
      'version': version,
      'coverage': {
        'minimum_line_percent': minimumCoverage,
        'low_file_threshold_percent': lowFileCoverageThreshold,
        'exclude': [for (final rule in coverageExcludes) rule.toJson()],
      },
      'maestro': {
        'expected_version': expectedMaestroVersion,
        'platforms': maestroPlatforms,
        'app_ids': {'ios': iosAppId, 'android': androidAppId},
        'done_command': doneCommand,
      },
      'evidence': {
        'build_dir': buildEvidenceDir,
        'committed_dir': committedEvidenceDir,
        'required_reports': requiredEvidenceReports,
      },
      'harness': {
        'required_files': requiredHarnessFiles,
        'required_directories': requiredHarnessDirectories,
        'generated_files': generatedFiles,
        'agent_skills': agentSkills,
      },
      'observability': {'acceptance_report_events': acceptanceReportEvents},
    };
  }
}

class CoverageExcludeRule {
  const CoverageExcludeRule({required this.kind, required this.value});

  static const _matchers = {'contains', 'starts_with', 'ends_with', 'equals'};

  final String kind;
  final String value;

  factory CoverageExcludeRule.fromYaml(yaml.YamlMap map) {
    if (map.length != 1) {
      throw FormatException('Coverage exclude rule must contain one matcher.');
    }
    final key = map.keys.single.toString();
    if (!_matchers.contains(key)) {
      throw FormatException('Unknown coverage exclude matcher: $key');
    }
    return CoverageExcludeRule(
      kind: key,
      value: map[map.keys.single].toString(),
    );
  }

  bool matches(String path) {
    return switch (kind) {
      'contains' => path.contains(value),
      'starts_with' => path.startsWith(value),
      'ends_with' => path.endsWith(value),
      'equals' => path == value,
      _ => throw FormatException('Unknown coverage exclude matcher: $kind'),
    };
  }

  Map<String, Object?> toJson() {
    return {kind: value};
  }
}

class CommandSpec {
  const CommandSpec(this.executable, this.arguments);

  final String executable;
  final List<String> arguments;
}

class GeneratedUiMap {
  const GeneratedUiMap({
    required this.content,
    required this.specCount,
    required this.targetCount,
  });

  final String content;
  final int specCount;
  final int targetCount;
}

class CoverageSummary {
  const CoverageSummary(this.files);

  final List<CoverageFile> files;

  int get foundLines => files.fold(0, (sum, file) => sum + file.foundLines);

  int get hitLines => files.fold(0, (sum, file) => sum + file.hitLines);

  double get percent {
    if (foundLines == 0) return 0;
    return hitLines * 100 / foundLines;
  }
}

class CoverageFile {
  const CoverageFile({
    required this.path,
    required this.foundLines,
    required this.hitLines,
  });

  final String path;
  final int foundLines;
  final int hitLines;

  double get percent {
    if (foundLines == 0) return 0;
    return hitLines * 100 / foundLines;
  }
}
