IMAGE_PATH="assets/images"
SUFFIX_PNG="png"
SUFFIX_SVG="svg"
WRITE_TO="lib/core/resources/images.dart"

{
  echo "/// This file is automatically generated, you should not edit it manually."
  echo "class Images {"
  echo ""
} > "./$WRITE_TO"

for files in "./$IMAGE_PATH"/*."$SUFFIX_PNG"
do
  fileName=$(basename "$files")
  withoutSuffix=$(basename "$files" ".$SUFFIX_PNG")
  # Convert snake_case to lowerCamelCase
  camelCase=$(echo "$withoutSuffix" | perl -pe 's/_([a-z])/\U$1/g')
  echo "  static const $camelCase = '$IMAGE_PATH/$fileName';" >> "./$WRITE_TO"
done

{
  echo "}"
} >> "./$WRITE_TO"